# Site settings
title: ANA PAULA MENDES
description: "A tech blog to share about my career"
baseurl: ""
url: ""

# User settings
username: Ana Paula Mendes
occupation: Senior Software Engineer | Consultant
user_title: Ana Paula Mendes
email: anapaula.ds.mendes@gmail.com
twitter_username: ananoterminal
github_username:  anapaulamendes
linkedin_public_url: anapauladsmendes/
disqus_username: ananoterminal
profile_picture: https://avatars0.githubusercontent.com/u/9610091?s=460&v=4

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  section_1:
    - title: home
      url: /
      key_trigger: 1
  section_2:
    - title: blog
      url: /blog
      key_trigger: 2
  section_3:
    - title: whoami
      url: /about
      key_trigger: 3
  section_4:
    - title: resume
      url: /AnaPaulaMendesResume.pdf
      key_trigger: 4

# projects in header index
projects:
  - name: Ana no Terminal
    url: https://ananoterminal.github.io/

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules', Gemfile, Gemfile.lock]
