# Site settings
title: Ana Paula Mendes
description: "A personal blog to share knowledge and my professional experience in the technology career."
baseurl: "https://anapaulamendes.github.io/"
url: "https://anapaulamendes.github.io/"

# User settings
username: ANA PAULA MENDES
user_title: Ana Paula Mendes
email: anapaula.ds.mendes@gmail.com
twitter_username: ananoterminal
github_username:  anapaulamendes
linkedin_public_url: ana-paula-mendes-22b55088/
disqus_username: ananoterminal
profile_picture: https://avatars0.githubusercontent.com/u/9610091?s=460&v=4

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  section_1:
    - title: home
      url: /
      key_trigger: 1
    - title: my posts
      url: /posts
      key_trigger: 2
    - title: series
      url: /series
      key_trigger: 3
    - title: tags
      url: /tags
      key_trigger: 4
    - title: about me
      url: /about
      key_trigger: 5
  section_2:
    - title: resume
      url: /AnaPaulaMendesResume.pdf
      key_trigger: r
    - title: talks & workshops
      url: /talks-workshops
      key_trigger: t

# projects in header index
projects:
  - name: Ana no Terminal
    url: http://ananoterminal.me/
  - name: Meninas Digitais Piauí
    url: https://meninasdigitaispiaui.github.io/
  - name: 100 Days of Code
    url: https://github.com/anapaulamendes/100-days-of-code
  - name: PyLadies Teresina
    url: https://github.com/anapaulamendes/pyladiesteresina.github.io

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules', Gemfile, Gemfile.lock]
